# Generated by Django 6.0.3 on 2026-04-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_pin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
